import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import vm from 'node:vm';
import os from 'node:os';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'ki-workspace-test-'));
const context={TextEncoder};vm.runInNewContext(await fs.readFile(path.join(root,'files.js'),'utf8')+'\nthis.makeMidi=buildMidi;',context);
await fs.writeFile(path.join(temp,'score.mid'),context.makeMidi({tempo:72,tracks:[{notes:[{pitch:60,start:0,duration:1}]}]}));
const dom=new JSDOM('');globalThis.DOMParser=dom.window.DOMParser;
const actualFetch=globalThis.fetch;globalThis.fetch=async input=>{const url=new URL(input);if(url.protocol==='file:')return new Response(await fs.readFile(url));return actualFetch(input);};
const {createOfficeFile,readDocument,zipBackup,unzipBackup}=await import(new URL('../office.mjs',import.meta.url));
const spec={title:'Abendlicht – Prüfung',blocks:[{type:'heading',text:'Überblick',level:1},{type:'paragraph',text:'Ein Dokument mit Umlauten: ÄÖÜ äöü ß.\nZweite Zeile.'},{type:'list',items:['Klavier','Violine']},{type:'table',rows:[['Instrument','Takte'],['Klavier',16],['Violine',8]]}]};
const word=await createOfficeFile({...spec,kind:'docx'});assert(word.size>1000);await fs.writeFile(path.join(temp,'test.docx'),new Uint8Array(await word.arrayBuffer()));const readWord=await readDocument({name:'test.docx'},await word.arrayBuffer());assert.match(readWord.text,/Überblick/);assert.match(readWord.text,/ÄÖÜ/);assert.match(readWord.text,/Klavier/);
const pdf=await createOfficeFile({...spec,kind:'pdf'});assert(pdf.size>1000);await fs.writeFile(path.join(temp,'test.pdf'),new Uint8Array(await pdf.arrayBuffer()));
const excel=await createOfficeFile({kind:'xlsx',sheets:[{name:'Musik',rows:[['Instrument','Takte'],['Klavier',16],['Violine',8],['Gesamt',{formula:'SUM(B2:B3)',result:24}]],freezeRows:1}]});await fs.writeFile(path.join(temp,'test.xlsx'),new Uint8Array(await excel.arrayBuffer()));let readSheet=await readDocument({name:'test.xlsx'},await excel.arrayBuffer());assert.match(readSheet.text,/SUM\(B2:B3\)/);assert.match(readSheet.text,/24/);
const changed=await createOfficeFile({kind:'xlsx',sourceFileId:'source',sheets:[{name:'Musik',updates:[{cell:'B2',value:32}]}]},excel);readSheet=await readDocument({name:'test.xlsx'},await changed.arrayBuffer());assert.match(readSheet.text,/32/);assert.match(readSheet.text,/Violine/);
const midi=await fs.readFile(path.join(temp,'score.mid'));const midiRead=await readDocument({name:'komposition.mid'},midi.buffer.slice(midi.byteOffset,midi.byteOffset+midi.byteLength));assert.match(midiRead.text,/noteOn/);assert.match(midiRead.text,/setTempo/);
const metadata={version:'2.0.0',chats:[{id:'chat',title:'Test',messages:[]}],files:[{id:'abc',name:'test.docx',type:word.type,category:'docx',extracted:readWord.text}]};const backup=await zipBackup(metadata,[{id:'abc',blob:word}]);const restored=await unzipBackup(backup);assert.equal(restored.records.length,1);assert.equal(restored.records[0].blob.size,word.size);assert.equal(restored.metadata.chats[0].title,'Test');
await assert.rejects(createOfficeFile({kind:'pdf',blocks:[{type:'nonsense'}]}),/Unbekannter/);await assert.rejects(createOfficeFile({kind:'xlsx',sheets:[{name:'x',updates:[{cell:'DROP',value:1}]}]}),/Zelladresse/);
console.log('PASS: DOCX generation and text roundtrip; PDF generation with Unicode, lists and table; XLSX values/formulas roundtrip; source-workbook copy with targeted edits; MIDI parsing; ZIP backup with original binary files; invalid-data rejection.');dom.window.close();await fs.rm(temp,{recursive:true,force:true});
