const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict'),{indexedDB}=require('fake-indexeddb');
const root=require('path').resolve(__dirname,'..')+'/';
const html=fs.readFileSync(root+'index.html','utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,'');
const dom=new JSDOM(html,{url:'https://example.test/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.AbortSignal=AbortSignal;w.Blob=Blob;w.File=class extends Blob{constructor(parts,name,options){super(parts,options);this.name=name;}};w.FileReader=class {readAsDataURL(blob){blob.arrayBuffer().then(b=>{this.result='data:'+blob.type+';base64,'+Buffer.from(b).toString('base64');this.onload();}).catch(e=>{this.error=e;this.onerror();});}};w.Response=Response;w.indexedDB=indexedDB;w.matchMedia=()=>({matches:false});w.URL.createObjectURL=()=> 'blob:preview';w.URL.revokeObjectURL=()=>{};
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1EAAAAASUVORK5CYII=';let requests=[],downloads=[];
w.fetch=async(url,options={})=>{requests.push({url,body:options.body&&JSON.parse(options.body)});let value;if(url.includes('images/models'))value={data:[{id:'test/image',name:'Image test',architecture:{input_modalities:['text','image'],output_modalities:['image']},supported_parameters:{input_references:{max:2}}}]};else if(url.includes('/models'))value={data:[{id:'test/vision',name:'Vision',architecture:{input_modalities:['text','image'],output_modalities:['text']}}]};else if(url.endsWith('/images'))value={data:[{b64_json:png,media_type:'image/png'}],usage:{cost:.04}};else if(url.includes('chat/completions'))value={choices:[{message:{content:'Ich sehe dein Bild.'}}]};else value=[];return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});};
const source=['vendor/marked.js','vendor/purify.js','files.js','uploads.js','images.js','model-info.js','app.js'].map(name=>fs.readFileSync(root+name,'utf8')).join('\n');w.eval(source+'\nObject.assign(window,{messageForAPI,pickAttachments,generateImage,storeOutputImages,appendImageCard,prepareChatMessages,sendMessage,changeWorkMode,currentChat,setStorage,getStorage,renderChat,stopRequest,getRecord:getFileRecord,putRecord:putFileRecord,listRecords:allFileRecords,getPending:()=>pendingAttachments,clearImageCache:()=>imagePreviewCache.clear()});');
w.eval('download=(name,data,type)=>window.savedDownload(name,data,type)');w.savedDownload=(...args)=>downloads.push(args);
function file(name,type){const f=new w.File([Uint8Array.from(atob(png),c=>c.charCodeAt(0))],name,{type});return f;}
const wait=()=>new Promise(r=>setTimeout(r,30));
(async()=>{await wait();w.setStorage('or_key','test-key');await w.pickAttachments({target:{files:[file('a.png','image/png'),file('b.png','image/png')]}});assert.equal(w.getPending().length,2);assert.equal(w.document.querySelectorAll('.attachment-thumbnail').length,2);const sent=await w.messageForAPI({role:'user',content:'Vergleiche',attachments:w.getPending()});assert.equal(sent.content.filter(p=>p.type==='image_url').length,2);
w.document.getElementById('work-mode').value='image';w.changeWorkMode();w.document.getElementById('user-text').value='Erzeuge daraus ein Aquarell';await w.sendMessage();const req=requests.find(r=>r.url.endsWith('/images'));assert.equal(req.body.input_references.length,2);assert.equal(req.body.model,'test/image');assert.equal(req.body.prompt.includes('Erzeuge daraus ein Aquarell'),true);let chat=w.currentChat();let bot=chat.messages.at(-1);assert(!bot.error);assert.equal(bot.attachments.length,1);assert.equal(bot.usage.cost,.04);assert(!JSON.stringify(JSON.parse(w.getStorage('or_chats'))).includes(png),'binary images not in localStorage');await wait();assert.equal(w.document.querySelectorAll('.image-card').length,3);const save=[...w.document.querySelectorAll('button')].filter(b=>b.textContent==='Bild speichern').at(-1);await save.onclick();assert(downloads[0][0].startsWith('bild-'));assert.equal(downloads[0][1].type,'image/png');assert.equal(downloads[0][1].size,68);
w.document.getElementById('user-text').value='Jetzt ohne Rahmen';await w.sendMessage();const edit=requests.filter(r=>r.url.endsWith('/images')).at(-1);assert.equal(edit.body.input_references.length,1);assert(edit.body.prompt.includes('Jetzt ohne Rahmen'));assert.equal(w.currentChat().messages.at(-1).attachments.length,1);
w.document.getElementById('work-mode').value='chat';w.changeWorkMode();w.document.getElementById('user-text').value='Beschreibe das Ergebnis';await w.sendMessage();const vision=requests.find(r=>r.url.endsWith('chat/completions'));assert.equal(vision.body.messages.at(-1).content.filter(p=>p.type==='image_url').length,1);assert.equal(w.currentChat().messages.at(-1).content,'Ich sehe dein Bild.');
const records=await w.listRecords();assert.equal(records.length,4);const {zipBackup,unzipBackup}=await import(root+'office.mjs');const zip=await zipBackup({chats:JSON.parse(w.getStorage('or_chats')),files:records.map(({blob,...r})=>r)},records);const restored=await unzipBackup(zip);assert.equal(restored.records.length,4);assert.equal(restored.records.at(-1).blob.size,68);w.clearImageCache();w.renderChat();await wait();assert.equal(w.document.querySelectorAll('.image-card').length,4);
const button=[...w.document.querySelectorAll('button')].find(b=>b.textContent==='Als Anhang verwenden');button.onclick();assert.equal(w.getPending().length,1);
// Reused text originals appear once in the request, with a reference on repetition.
const original={id:'text-original',name:'source.txt',type:'text/plain',category:'text',blob:new Blob(['UNIQUE_SOURCE_CONTENT']),extracted:'UNIQUE_SOURCE_CONTENT'};await w.putRecord(original);
const repeated=await w.prepareChatMessages([{role:'user',content:'Lies',attachments:[original]},{role:'assistant',content:'Gelesen'},{role:'user',content:'Prüfe erneut',attachments:[original]}]);const requestText=JSON.stringify(repeated);assert.equal(requestText.split('UNIQUE_SOURCE_CONTENT').length-1,1);assert(requestText.includes('Inhalt unverändert'));assert.equal(repeated.length,3);
// A delayed provider remains pending beyond five minutes. Only manual stop aborts it.
const realFetch=w.fetch,realNow=w.Date.now,realInterval=w.setInterval,realClear=w.clearInterval;let tick,cleared=false,clock=1000,requestSignal;
w.Date.now=()=>clock;w.setInterval=fn=>{tick=fn;return 123;};w.clearInterval=id=>{if(id===123)cleared=true;};
w.document.getElementById('work-mode').value='image';w.changeWorkMode();w.document.getElementById('user-text').value='Langsame Bildgenerierung';
w.fetch=async(url,options)=>{requestSignal=options.signal;return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new w.DOMException('Abgebrochen','AbortError')),{once:true}));};
const pending=w.sendMessage();await wait();clock+=360000;tick();assert.equal(requestSignal.aborted,false);assert.equal(w.currentChat().messages.at(-1).pending,true);assert(w.document.getElementById('request-progress').textContent.includes('6:00'));w.stopRequest();await pending;assert.equal(requestSignal.aborted,true);assert.equal(w.currentChat().messages.at(-1).content,'Anfrage von dir gestoppt.');assert.equal(w.document.getElementById('request-progress').hidden,true);assert(cleared);
// Manual stop preserves text already received from a streaming chat response.
w.fetch=async(url,options)=>{const stream=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('data: {"choices":[{"delta":{"content":"Bisherige Antwort"}}]}\n\n'));options.signal.addEventListener('abort',()=>c.error(new w.DOMException('Abgebrochen','AbortError')),{once:true});}});return new Response(stream,{headers:{'Content-Type':'text/event-stream'}});};
w.document.getElementById('work-mode').value='chat';w.changeWorkMode();w.document.getElementById('user-text').value='Langsame Antwort';const streaming=w.sendMessage();await wait();w.stopRequest();await streaming;const stopped=w.currentChat().messages.at(-1);assert.equal(stopped.content,'Bisherige Antwort');assert.equal(stopped.partial,true);assert.equal(stopped.pending,false);assert.equal(w.document.getElementById('request-progress').hidden,true);
w.fetch=realFetch;w.Date.now=realNow;w.setInterval=realInterval;w.clearInterval=realClear;
console.log('PASS: delayed image request beyond five minutes, elapsed display, manual stop, streaming partial text retained, timer cleanup.');
console.log('PASS: multiple original image inputs, thumbnails, dedicated image request, durable binary output, save/download, reference edit, generated image follow-up in vision chat, reuse.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{w.close()});
